name: Pipeline

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compilacao:
    name: Compilação
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configura JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn -B compile --file pom.xml
      
  qualidade_codigo:
    name: Qualidade de Código
    needs: compilacao
    runs-on: ubuntu-latest        
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Adiciona permissão para mvnw
      run: chmod +x mvnw
    - name: Análise SonarCloud
      run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-devops-project
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        
        
  testes:
    name: Testes automatizados
    needs: qualidade_codigo
    runs-on: ubuntu-latest    
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configura JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Testes Unitários
      run: mvn -B test --file pom.xml
